[package]
name = "eggshell"
version = "0.0.1"
edition = "2021"
exclude = ["test.log", "data/", ".*"]
license = "GPL-3.0-or-later"

[lib]
# The name of the native library.
# This is the name which will be used in Python to import the library
# If you change this, you must also change the name of the
# `#[pymodule]` in `src/lib.rs`.
name = "eggshell"
# "cdylib" is necessary to produce a shared library for Python to import from.
# To use it from both Python and Rust, you need "cdylib" and "rlib".
crate-type = ["cdylib", "rlib"]

[dependencies]
csv = "1.3.0"
egg = { version = "0.9.5", features = ["serde-1"] }
hashbrown = { version = "0.14.5", features = ["rayon", "serde"] }
log = "0.4.21"
ordered-float = { version = "4.2.1", features = ["serde"] }
pyo3 = { version = "0.21.2", features = ["hashbrown"] }
rayon = "1.10.0"
serde = { version = "1.0.203", features = ["derive"] }
smallvec = { version = "1.13.2", features = ["const_generics", "serde"] }
thiserror = "1.0.61"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }


[[bench]]
name = "bench"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
