# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import eggshell
import typing

class PyRecExpr:
    r"""
    Wrapper type for Python
    """
    def __new__(cls,s_expr_str:str): ...
    @staticmethod
    def batch_new(s_expr_strs:typing.Sequence[str]) -> list[PyRecExpr]:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def arity(self, position:int) -> int:
        ...

    def to_data(self, variable_names:typing.Sequence[str], ignore_unknown:bool) -> TreeData:
        ...

    @staticmethod
    def to_data_batch(rec_exprs:typing.Sequence[PyRecExpr], variable_names:typing.Sequence[str], ignore_unknown:bool) -> list[TreeData]:
        ...

    @staticmethod
    def from_data(tree_data:TreeData, variable_names:typing.Sequence[str]) -> PyRecExpr:
        ...

    @staticmethod
    def named_symbols() -> list[str]:
        ...


def eqsat_check(start:PyRecExpr,goal:PyRecExpr,iter_limit:int) -> tuple[int, str, str]:
    ...

def many_eqsat_check(starts:typing.Sequence[PyRecExpr],goal:PyRecExpr,iter_limit:int) -> list[tuple[int, str, str]]:
    ...

