# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import numpy
import numpy.typing
import typing

class PyNode:
    def __new__(cls,node_name:str, children:typing.Sequence[int]): ...
    def name(self) -> str:
        ...

    def is_leaf(self) -> bool:
        ...

    def children(self) -> list[int]:
        ...

    def features(self, variable_names:typing.Sequence[str], ignore_unknown:bool) -> list[float]:
        ...


class PyRecExpr:
    r"""
    Wrapper type for Python
    """
    def __new__(cls,s_expr_str:str): ...
    @staticmethod
    def many_new(s_expr_strs:typing.Sequence[str]) -> list[PyRecExpr]:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    def children_of(self, node:PyNode) -> list[PyNode]:
        ...

    def arity(self, position:int) -> int:
        ...

    def size(self) -> int:
        ...

    def depth(self) -> int:
        ...

    def count_symbols(self, variable_names:typing.Sequence[str], ignore_unknown:bool) -> list[int]:
        ...

    def featurize_simple(self, variable_names:typing.Sequence[str], ignore_unknown:bool) -> numpy.typing.NDArray[numpy.float64]:
        ...


def eqsat_check(start:PyRecExpr,goal:PyRecExpr,iter_limit:int) -> tuple[int, str, str]:
    ...

def feature_names_simple() -> list[str]:
    ...

def many_eqsat_check(starts:typing.Sequence[PyRecExpr],goal:PyRecExpr,iter_limit:int) -> list[tuple[int, str, str]]:
    ...

def many_featurize_simple(exprs:typing.Sequence[PyRecExpr],variable_names:typing.Sequence[str],ignore_unknown:bool) -> numpy.typing.NDArray[numpy.float64]:
    ...

