# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from . import arithmetic
from . import halide
from . import rise
from . import simple

class EggshellException(builtins.Exception):
    r"""
    Eggshell internal error.
    """
    ...

class FirstErrorDistance:
    @property
    def n_hits(self) -> builtins.int: ...
    @property
    def n_misses(self) -> builtins.int: ...
    def __new__(cls) -> FirstErrorDistance: ...
    def hit_ids(self) -> builtins.list[builtins.int]: ...
    def hit_probabilities(self) -> builtins.list[typing.Optional[builtins.float]]: ...
    def miss_ids(self) -> builtins.list[builtins.int]: ...
    def miss_probabilities(self) -> builtins.list[typing.Optional[builtins.float]]: ...

